version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: recepti-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recepti
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"   # da ne pride do konflikta z lokalnim MySQL
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 25s

  app:
    build: ./recepti
    container_name: recepti-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/recepti
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password

  frontend:
    build: ./recepti-frontend
    container_name: recepti-frontend
    ports:
      - "3000:80"
    depends_on:
      - app

volumes:
  mysql_data:
